version: '3'
services:
  mysql:
    build: ./mysql
    image: mysql5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ARK_Bleeing
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db-data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init/:/docker-entrypoint-initdb.d
      - ./mysql/log:/var/log/mysql
  golang:
    links:
      - mysql
    build: ./golang
    ports:
      - "8090:8080"
    volumes:
      - ./golang/api:/go/src/api
    #command: sh ./scripts/start_app.sh
  vue:
    build: ./client
    ports:
      - 9050:9050
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
    command: /bin/sh
volumes:
  db-data:
    driver: local

#参考にした
#https://qiita.com/thimi0412/items/61a27364a09d60a86708
#https://qiita.com/kkeisuke/items/7cd4d5834386666faab3
#また docker exec -it コンテナ名では　alpine linux　では /bin/ash

#docker exec -it vue_js /bin/ash で実行